FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist

# using instead 'RUN npm install --production', because of some dev dependencies
COPY --from=builder /app/node_modules ./node_modules

COPY package.json .
# COPY .env .

# not using for Render hosting
# ENV PORT=$PORT

# EXPOSE 3001

CMD [ "node", "dist/main" ]